/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#d4e4fa",
        "surface-tint": "#7bd0ff",
        "secondary": "#d0bcff",
        "on-primary-container": "#004965",
        "on-secondary": "#3c0091",
        "on-primary-fixed": "#001e2c",
        "on-secondary-container": "#c4abff",
        "surface-container-highest": "#273647",
        "on-tertiary": "#552100",
        "on-surface-variant": "#bdc8d1",
        "surface-variant": "#273647",
        "on-tertiary-fixed": "#341100",
        "surface-container-low": "#0d1c2d",
        "tertiary-container": "#ff975d",
        "inverse-primary": "#00668a",
        "tertiary-fixed-dim": "#ffb690",
        "inverse-on-surface": "#233143",
        "primary-container": "#38bdf8",
        "tertiary": "#ffbf9e",
        "background": "#051424",
        "on-surface": "#d4e4fa",
        "tertiary-fixed": "#ffdbca",
        "surface-container-lowest": "#010f1f",
        "on-secondary-fixed-variant": "#5516be",
        "on-tertiary-container": "#743000",
        "on-primary": "#00354a",
        "surface-container-high": "#1c2b3c",
        "outline": "#87929a",
        "on-secondary-fixed": "#23005c",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#783200",
        "surface-dim": "#051424",
        "surface-container": "#122131",
        "surface": "#051424",
        "secondary-fixed": "#e9ddff",
        "on-error": "#690005",
        "surface-bright": "#2c3a4c",
        "error": "#ffb4ab",
        "primary-fixed": "#c4e7ff",
        "secondary-fixed-dim": "#d0bcff",
        "on-background": "#d4e4fa",
        "outline-variant": "#3e484f",
        "on-primary-fixed-variant": "#004c69",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#7bd0ff",
        "secondary-container": "#571bc1",
        "primary": "#8ed5ff",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "mono-lg": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "mono-md": ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
